#!/bin/bash

# Script to create GitHub issues from Dependabot alerts
# This is a workaround since GitHub Actions can't access Dependabot API

REPO="RogerioDoCarmo/curriculo"

# Get all open Dependabot alerts
echo "🔍 Fetching open Dependabot alerts..."
alerts=$(gh api repos/$REPO/dependabot/alerts --jq '.[] | select(.state == "open")')

# Counter for created issues
created=0
skipped=0

# Process each alert
echo "$alerts" | jq -c '.' | while read -r alert; do
  # Extract alert details
  alert_number=$(echo "$alert" | jq -r '.number')
  severity=$(echo "$alert" | jq -r '.security_advisory.severity' | tr '[:lower:]' '[:upper:]')
  package_name=$(echo "$alert" | jq -r '.security_vulnerability.package.name')
  vulnerable_version=$(echo "$alert" | jq -r '.security_vulnerability.vulnerable_version_range')
  patched_version=$(echo "$alert" | jq -r '.security_vulnerability.first_patched_version.identifier // "Not available"')
  cve=$(echo "$alert" | jq -r '.security_advisory.cve_id // "N/A"')
  cvss_score=$(echo "$alert" | jq -r '.security_advisory.cvss.score // "N/A"')
  summary=$(echo "$alert" | jq -r '.security_advisory.summary')
  description=$(echo "$alert" | jq -r '.security_advisory.description')
  ghsa_id=$(echo "$alert" | jq -r '.security_advisory.ghsa_id')
  html_url=$(echo "$alert" | jq -r '.html_url')
  scope=$(echo "$alert" | jq -r '.dependency.scope')
  
  # Get references
  references=$(echo "$alert" | jq -r '.security_advisory.references[] | "- \(.url)"' | tr '\n' '\n')
  
  # Determine priority label
  if [[ "$severity" == "CRITICAL" || "$severity" == "HIGH" ]]; then
    priority_label="priority: high"
  elif [[ "$severity" == "LOW" ]]; then
    priority_label="priority: low"
  else
    priority_label="priority: medium"
  fi
  
  # Check if issue already exists
  existing_issue=$(gh issue list --repo $REPO --label "security,dependabot" --state open --search "Alert #$alert_number" --json number --jq '.[0].number')
  
  if [[ -n "$existing_issue" ]]; then
    echo "⏭️  Issue already exists for alert #$alert_number (issue #$existing_issue), skipping"
    ((skipped++))
    continue
  fi
  
  # Create issue title
  title="🔒 [$severity] Security vulnerability in $package_name"
  
  # Determine save flag
  save_flag=""
  if [[ "$scope" == "development" ]]; then
    save_flag="--save-dev"
  fi
  
  # Create issue body
  body="## 🚨 Dependabot Security Alert #$alert_number

**Severity**: $severity (CVSS: $cvss_score)
**Package**: \`$package_name\`
**Vulnerable Version**: $vulnerable_version
**Patched Version**: $patched_version
**CVE**: $cve

### Summary
$summary

### Description
$description

### References
$references

### Recommended Action
"
  
  if [[ "$patched_version" != "Not available" ]]; then
    body+="Update \`$package_name\` to version \`$patched_version\` or later."
  else
    body+="Review the security advisory and apply the recommended mitigation."
  fi
  
  body+="

### Steps to Fix
1. Review the security advisory details above
2. Update the dependency in \`package.json\`:
   \`\`\`bash
   npm install $package_name@${patched_version:-latest} $save_flag
   \`\`\`
3. Run tests to ensure compatibility:
   \`\`\`bash
   npm test
   npm run test:e2e
   \`\`\`
4. Commit and push changes:
   \`\`\`bash
   git add package.json package-lock.json
   git commit -m \"fix(deps): update $package_name to $patched_version (security fix)\"
   git push
   \`\`\`
5. Verify the alert is resolved in GitHub Security tab

### Related Links
- [Dependabot Alert #$alert_number]($html_url)
- [GitHub Security Advisory](https://github.com/advisories/$ghsa_id)"
  
  if [[ "$cve" != "N/A" ]]; then
    body+="
- [CVE Details](https://cve.mitre.org/cgi-bin/cvename.cgi?name=$cve)"
  fi
  
  body+="

---

**Alert #$alert_number** | Auto-generated by Dependabot | $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  
  # Create the issue
  issue_url=$(gh issue create \
    --repo $REPO \
    --title "$title" \
    --body "$body" \
    --label "security,dependabot,$priority_label,automated")
  
  if [[ -n "$issue_url" ]]; then
    issue_number=$(echo "$issue_url" | grep -oE '[0-9]+$')
    echo "✅ Created issue #$issue_number for alert #$alert_number ($severity - $package_name)"
    ((created++))
  else
    echo "❌ Failed to create issue for alert #$alert_number"
  fi
  
  # Small delay to avoid rate limiting
  sleep 1
done

echo ""
echo "📊 Summary:"
echo "  ✅ Issues created: $created"
echo "  ⏭️  Issues skipped: $skipped"
